Add SNR property according to datasheet
adafruit/Adafruit_CircuitPython_RFM9x pull request #59
Opened 2021-01-28 19:42 UTC by AdamLeyshon

Hello, I have implemented what I believe to be the correct function according to the datasheet for the RFM95W 
(RFM95W-V2.0-1.pdf from HOPERF)

The register is at 0x19, it 8 bits wide and is a signed values stored as a single byte using two's complement and should be divided by 4 to get the dB value.

Tested on my own AdaFruit RFM95W Bonnet for Raspberry Pi and AdaFruit RFM95W Breakout board connected to a Raspberry Pi Pico running the latest Circuit Python (6.2 beta)

I receive values between 6 and 9 when the transmitting station is near by,

Unfortunately I have nothing to compare this value against to determine if what the hardware says is correct.

Please let me know if the implementation is incorrect.

2021-01-28 19:48 UTC, brentru commented
@jerryneedell  do you have a chance to look at this?

2021-01-28 19:50 UTC, jerryneedell commented
@brentru not yet -- will take a look.

2021-01-28 20:20 UTC, jerryneedell requested changes
This looks good to me. One suggestion:
For the RSSI - we have 2 ways to read it. 
the .rssi property is the instantaneous RSSI stored
the .last_rssi is saved immediately after the packet is received.
I just ran some tests and I get the same reading fo riot, but as I recall, there were times when they were different . I don't know if the same applies to SNR.

If you want, we could add .last_snr in the same way -- I tried it and as with the RSSI, I get the same reading

here are the changes I made:
```
pi@gjnpilora:~/projects/blinka/rfm9x_ack $ diff adafruit_rfm9x.py ~/projects/adafruit_github/Adafruit_CircuitPython_RFM9x/adafruit_rfm9x.py 
289,293d288
<         self.last_snr = 0.0
<         """The SNR of the last received packet. Stored when the packet was received.
<            The instantaneous SNR value may not be accurate once the
<            operating mode has been changed.
<         """
790,791d784
<         # save last RSSI reading
<         self.last_snr = self.snr
```

As to the value returned, I have no way to determine its correctness but I think you have implemented it correctly.

Let me know what you think of adding the .last_snr properly as well.

2021-01-28 20:31 UTC, AdamLeyshon commented
Sound like a good idea to implement a "last" SNR as well to prevent the value changing in the register after receiving a packet but before we read the value after processing the current packet.

28 Jan 2021 20:21:19 jerryneedell <notifications@github.com>:

> @jerryneedell requested changes on this pull request.
> 
> This looks good to me. One suggestion:
> For the RSSI - we have 2 ways to read it.
> the .rssi property is the instantaneous RSSI stored
> the .last_rssi is saved immediately after the packet is received.
> I just ran some tests and I get the same reading fo riot, but as I recall, there were times when they were different . I don't know if the same applies to SNR.
> 
> If you want, we could add .last_snr in the same way -- I tried it and as with the RSSI, I get the same reading
> 
> here are the changes I made:
> 
> pi@gjnpilora:~/projects/blinka/rfm9x_ack $ diff adafruit_rfm9x.py ~/projects/adafruit_github/Adafruit_CircuitPython_RFM9x/adafruit_rfm9x.py 289,293d288 <         self.last_snr = 0.0 <         """The SNR of the last received packet. Stored when the packet was received. <            The instantaneous SNR value may not be accurate once the <            operating mode has been changed. <         """ 790,791d784 <         # save last RSSI reading <         self.last_snr = self.snrAs to the value returned, I have no way to determine its correctness but I think you have implemented it correctly.
> 
> Let me know what you think of adding the .last_snr properly as well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/pull/59#pullrequestreview-578708596], or unsubscribe[https://github.com/notifications/unsubscribe-auth/ABXBTVVXZ775W2TY64TDNELS4HBLLANCNFSM4WXT3VFA]. [https://github.com/notifications/beacon/ABXBTVUGQOTOVE3DAKRP7QDS4HBLLA5CNFSM4WXT3VFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEJ7GI5A.gif]
>

2021-01-28 20:38 UTC, jerryneedell commented
Great. If you can implement that and push a new commit, it should be ready to go.
Thanks for adding this.

2021-01-28 21:51 UTC, jerryneedell commented
Here is more information on the history of "last_rssi" implementation https://github.com/adafruit/Adafruit_CircuitPython_RFM69/issues/22
It was originally implemented on the RFM69 where it apparently had some impact. It is not clear if it matters for the RFM9x but it also "does no harm" so I think we may as well continue with it for RSSI and SNR.

2021-01-29 18:50 UTC, AdamLeyshon commented
I've implemented the requested changes for adding last_snr attribute to the class.

2021-01-29 18:58 UTC, jerryneedell approved these changes
Thank you! -- Looks good to me!  Tested on Raspberry Pi ZeroW with RFM9x Bonnet.

2021-01-29 18:58 UTC, jerryneedell commented
@brentru OK to merge this?

2021-01-29 19:37 UTC, brentru commented
@jerryneedell  Looks OK to me, go ahead :)

2021-01-29 19:55 UTC, merged

2021-01-29 20:04 UTC, AdamLeyshon commented
Thanks all, Hope to contribute more in future :)

2021-01-29 20:06 UTC, jerryneedell commented
@AdamLeyshon Thank you!   We look forward to future contributions!

2021-01-29 20:07 UTC, jerryneedell commented
BTW -- I also made a new release - v 2.1.2  -- should be available via PyPy soon and in the library bundle tonight.